<?php

return [
    'HAI' => [
      '1m','2m','3m','4m','5m','6m','7m','8m','9m',
      '1p','2p','3p','4p','5p','6p','7p','8p','9p',
      '1s','2s','3s','4s','5s','6s','7s','8s','9s',
      'e','s','w','n','h','r','c',
    ],

    'POSITION' => [
        'USER' => 1,
        'SIMO' => 2,
        'TOI' => 3,
        'KAMI' => 4,
    ],

    'HAI_TYPE' => [
        'MAN' => 1,
        'PIN' => 2,
        'SOU' => 3,
        'OTHER' => 4,
    ],

    'YAKU_NAME' => [
        'REACH' => '立直',
        'SOKU' => '一発',
        'TUMO' => '門前清自摸和',
        'BAKAZE' => '場風',
        'ZIKAZE' => '自風',
        'TYUN' => '中',
        'HAKU' => '白',
        'HATU' => '發',
        'TANYAO' => '断么九',
        'TANYAO_KUI' => '断么九',
        'PINHU' => '平和',
        'IPEKO' => '一盃口',
        'HAITEI' => '海底撈月',
        'HOUTEI' => '河底撈魚',
        'RINSHAN' => '嶺上開花',
        'THANKAN' => '槍槓',
        'W_REACH' => 'ダブル立直',
        'SANSYOKU_DOUZYUN' => '三色同順',
        'SANSYOKU_DOUZYUN_KUI' => '三色同順',
        'SANSYOKU_DOUKOU' => '三色同刻',
        'SANANKO' => '三暗刻',
        'ITTU' => '一気通貫',
        'ITTU_KUI' => '一気通貫',
        'TITOI' => '七対子',
        'TOITOI' => '対々和',
        'TYANTA' => '混全帯幺九',
        'TYANTA_KUI' => '混全帯幺九',
        'SANKANTU' => '三槓子',
        'RYANPEKO' => '二盃口',
        'ZYUNTYAN' => '純全帯公九',
        'ZYUNTYAN_KUI' => '純全帯公九',
        'HONITU' => '混一色',
        'HONITU_KUI' => '混一色',
        'SYOUSANGEN' => '小三元',
        'HONROTO' => '混老頭',
        'TINITU' => '清一色',
        'TINITU_KUI' => '清一色',
        'SUANKO' => '四暗刻',
        'DAISANGEN' => '大三元',
        'KOKUSHI' => '国士無双',
        'RYUISO' => '緑一色',
        'TUISO' => '字一色',
        'TINROTO' => '清老頭',
        'SUKANTU' => '四槓子',
        'SHOSUSHI' => '小四喜',
        'TYUREN' => '九蓮宝燈',
        'TIHO' => '地和',
        'TENHO' => '天和',
        'SUTTAN' => '四暗刻単騎',
        'KOKUSHI_13' => '国士無双13面待ち',
        'ZYUNSEI_TYUREN' => '純正九蓮宝燈',
        'DAISUSHI' => '大四喜',
    ],

    'YAKU_HAN' => [
        'REACH' => 1,
        'SOKU' => 1,
        'TUMO' => 1,
        'BAKAZE' => 1,
        'ZIKAZE' => 1,
        'TYUN' => 1,
        'HAKU' => 1,
        'HATU' => 1,
        'TANYAO' => 1,
        'TANYAO_KUI' => 1,
        'PINHU' => 1,
        'IPEKO' => 1,
        'HAITEI' => 1,
        'HOUTEI' => 1,
        'RINSHAN' => 1,
        'THANKAN' => 1,
        'W_REACH' => 2,
        'SANSYOKU_DOUZYUN' => 2,
        'SANSYOKU_DOUZYUN_KUI' => 1,
        'SANSYOKU_DOUKOU' => 2,
        'SANANKO' => 2,
        'ITTU' => 2,
        'ITTU_KUI' => 1,
        'TITOI' => 2,
        'TOITOI' => 2,
        'TYANTA' => 2,
        'TYANTA_KUI' => 1,
        'SANKANTU' => 2,
        'RYANPEKO' => 3,
        'ZYUNTYAN' => 3,
        'ZYUNTYAN_KUI' => 2,
        'HONITU' => 3,
        'HONITU_KUI' => 2,
        'SYOUSANGEN' => 2,
        'HONROTO' => 2,
        'TINITU' => 6,
        'TINITU_KUI' => 5,
        'SUANKO' => 13,
        'DAISANGEN' => 13,
        'KOKUSHI' => 13,
        'RYUISO' => 13,
        'TUISO' => 13,
        'TINROTO' => 13,
        'SUKANTU' => 13,
        'SHOSUSHI' => 13,
        'TYUREN' => 13,
        'TIHO' => 13,
        'TENHO' => 13,
        'SUTTAN' => 26,
        'KOKUSHI_13' => 26,
        'ZYUNSEI_TYUREN' => 26,
        'DAISUSHI' => 26,

    ],
];